name: '03 - Execução por Push'

on:
  push:

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install

      - run: npm test

      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Testes Automatizados
          path: results.xml
          reporter: java-junit

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: relatorio-testes
          path: results.xml